apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-router-frontend
  namespace: mcp-router
  labels:
    app: mcp-router-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-router-frontend
  template:
    metadata:
      labels:
        app: mcp-router-frontend
    spec:
      containers:
      - name: frontend
        image: mcp-router-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://mcp-router-backend-service:8000"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-router-frontend-service
  namespace: mcp-router
  labels:
    app: mcp-router-frontend
spec:
  selector:
    app: mcp-router-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mcp-router-frontend-hpa
  namespace: mcp-router
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mcp-router-frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80